import type { Project, Task } from "./types";

export const SEED_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Lightning Bounties Platform",
    description: "AI-powered marketplace for GitHub issue bounties. Real-time bidding, automated code review.",
    status: "active",
    tags: [{ id: "t1", name: "platform", color: "#f97316" }],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-03-15T14:30:00Z",
  },
  {
    id: "proj-2",
    name: "Developer Dashboard",
    description: "Internal analytics dashboard for tracking agent performance and payout metrics.",
    status: "active",
    tags: [{ id: "t2", name: "internal", color: "#3b82f6" }],
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-03-20T11:00:00Z",
  },
  {
    id: "proj-3",
    name: "Mobile App v2",
    description: "React Native rewrite of the mobile client. Notifications, wallet integration.",
    status: "completed",
    tags: [{ id: "t3", name: "mobile", color: "#8b5cf6" }],
    createdAt: "2023-11-01T08:00:00Z",
    updatedAt: "2024-01-30T17:00:00Z",
  },
];

export const SEED_TASKS: Task[] = [
  // proj-1 tasks
  {
    id: "task-1",
    projectId: "proj-1",
    title: "Implement bidding auction engine",
    description: "Core real-time auction logic with WebSocket support for live bid updates.",
    status: "done",
    priority: "high",
    tags: [{ id: "t1", name: "backend", color: "#f97316" }],
    assignee: "alice@example.com",
    dueDate: "2024-02-28",
    order: 0,
    createdAt: "2024-01-11T09:00:00Z",
    updatedAt: "2024-02-25T16:00:00Z",
  },
  {
    id: "task-2",
    projectId: "proj-1",
    title: "Build agent scoring rubric",
    description: "Multi-dimensional scoring: correctness, style, test coverage, security.",
    status: "in-progress",
    priority: "high",
    tags: [{ id: "t4", name: "ai", color: "#10b981" }],
    assignee: "bob@example.com",
    dueDate: "2024-04-10",
    order: 1,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-03-18T09:30:00Z",
  },
  {
    id: "task-3",
    projectId: "proj-1",
    title: "Add CSV export for payouts",
    description: "Export payout history as CSV for accounting integration.",
    status: "todo",
    priority: "medium",
    tags: [{ id: "t5", name: "feature", color: "#6366f1" }],
    assignee: "",
    dueDate: null,
    order: 2,
    createdAt: "2024-02-01T11:00:00Z",
    updatedAt: "2024-02-01T11:00:00Z",
  },
  {
    id: "task-4",
    projectId: "proj-1",
    title: "Write integration tests for API",
    description: "Cover all /api/bids and /api/bounties endpoints with realistic fixtures.",
    status: "blocked",
    priority: "medium",
    tags: [{ id: "t6", name: "testing", color: "#ec4899" }],
    assignee: "alice@example.com",
    dueDate: "2024-03-31",
    order: 3,
    createdAt: "2024-02-10T14:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
  },
  {
    id: "task-5",
    projectId: "proj-1",
    title: "Dark mode for marketplace UI",
    description: "Implement system-aware dark mode using CSS variables and Tailwind.",
    status: "todo",
    priority: "low",
    tags: [{ id: "t7", name: "ui", color: "#14b8a6" }],
    assignee: "",
    dueDate: null,
    order: 4,
    createdAt: "2024-02-20T12:00:00Z",
    updatedAt: "2024-02-20T12:00:00Z",
  },
  // proj-2 tasks
  {
    id: "task-6",
    projectId: "proj-2",
    title: "Revenue breakdown chart",
    description: "Bar chart showing daily revenue split by bounty category.",
    status: "done",
    priority: "high",
    tags: [{ id: "t8", name: "charts", color: "#f97316" }],
    assignee: "carol@example.com",
    dueDate: "2024-02-15",
    order: 0,
    createdAt: "2024-02-03T09:00:00Z",
    updatedAt: "2024-02-14T17:00:00Z",
  },
  {
    id: "task-7",
    projectId: "proj-2",
    title: "Agent leaderboard table",
    description: "Sortable table of top agents by earnings, win rate, response time.",
    status: "in-progress",
    priority: "medium",
    tags: [{ id: "t8", name: "charts", color: "#f97316" }],
    assignee: "carol@example.com",
    dueDate: "2024-04-05",
    order: 1,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-03-19T11:30:00Z",
  },
  {
    id: "task-8",
    projectId: "proj-2",
    title: "Alerting for anomaly detection",
    description: "Email alerts when bid volume drops below threshold.",
    status: "todo",
    priority: "low",
    tags: [{ id: "t9", name: "infra", color: "#64748b" }],
    assignee: "",
    dueDate: null,
    order: 2,
    createdAt: "2024-03-01T13:00:00Z",
    updatedAt: "2024-03-01T13:00:00Z",
  },
  {
    id: "task-9",
    projectId: "proj-2",
    title: "User retention cohort analysis",
    description: "Weekly cohort retention heatmap for developer accounts.",
    status: "todo",
    priority: "medium",
    tags: [{ id: "t10", name: "analytics", color: "#0ea5e9" }],
    assignee: "bob@example.com",
    dueDate: "2024-04-20",
    order: 3,
    createdAt: "2024-03-05T14:00:00Z",
    updatedAt: "2024-03-05T14:00:00Z",
  },
  {
    id: "task-10",
    projectId: "proj-2",
    title: "Export dashboard as PDF",
    description: "One-click PDF export of the full analytics dashboard.",
    status: "blocked",
    priority: "low",
    tags: [{ id: "t5", name: "feature", color: "#6366f1" }],
    assignee: "alice@example.com",
    dueDate: null,
    order: 4,
    createdAt: "2024-03-10T15:00:00Z",
    updatedAt: "2024-03-10T15:00:00Z",
  },
  // proj-3 tasks
  {
    id: "task-11",
    projectId: "proj-3",
    title: "React Native navigation setup",
    description: "Stack and tab navigators, deep linking config.",
    status: "done",
    priority: "high",
    tags: [{ id: "t3", name: "mobile", color: "#8b5cf6" }],
    assignee: "carol@example.com",
    dueDate: "2023-12-01",
    order: 0,
    createdAt: "2023-11-02T10:00:00Z",
    updatedAt: "2023-11-30T18:00:00Z",
  },
  {
    id: "task-12",
    projectId: "proj-3",
    title: "Lightning wallet integration",
    description: "Connect to LND node, sign transactions, display balance.",
    status: "done",
    priority: "high",
    tags: [{ id: "t11", name: "wallet", color: "#f59e0b" }],
    assignee: "bob@example.com",
    dueDate: "2024-01-15",
    order: 1,
    createdAt: "2023-11-10T09:00:00Z",
    updatedAt: "2024-01-14T20:00:00Z",
  },
  {
    id: "task-13",
    projectId: "proj-3",
    title: "Push notification system",
    description: "FCM integration for bid updates and bounty alerts.",
    status: "done",
    priority: "medium",
    tags: [{ id: "t3", name: "mobile", color: "#8b5cf6" }],
    assignee: "alice@example.com",
    dueDate: "2024-01-20",
    order: 2,
    createdAt: "2023-12-01T11:00:00Z",
    updatedAt: "2024-01-18T14:00:00Z",
  },
  {
    id: "task-14",
    projectId: "proj-3",
    title: "Offline mode with local cache",
    description: "SQLite caching layer for browsing bounties without network.",
    status: "done",
    priority: "medium",
    tags: [{ id: "t3", name: "mobile", color: "#8b5cf6" }],
    assignee: "carol@example.com",
    dueDate: "2024-01-25",
    order: 3,
    createdAt: "2023-12-05T12:00:00Z",
    updatedAt: "2024-01-22T16:00:00Z",
  },
  {
    id: "task-15",
    projectId: "proj-3",
    title: "App Store submission",
    description: "Screenshots, metadata, TestFlight beta, final review submission.",
    status: "done",
    priority: "high",
    tags: [{ id: "t3", name: "mobile", color: "#8b5cf6" }],
    assignee: "bob@example.com",
    dueDate: "2024-01-30",
    order: 4,
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-30T17:00:00Z",
  },
];
